# Generated by Django 4.1.5 on 2023-10-07 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShortCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='short_courses/')),
                ('amounts', models.ManyToManyField(to='course.amount')),
            ],
        ),
    ]
