# Generated by Django 4.1.5 on 2023-10-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourse',
            name='amounts',
            field=models.ManyToManyField(related_name='short_courses', to='course.amount'),
        ),
    ]
