# Generated by Django 4.1.5 on 2023-10-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_alter_shortcourse_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourse',
            name='amounts',
            field=models.ManyToManyField(to='course.amount'),
        ),
    ]
