# Generated by Django 4.1.5 on 2023-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_shortcourse_amounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourse',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
