# Generated by Django 4.1.5 on 2023-10-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_shortcourse_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortcourse',
            name='status',
            field=models.CharField(choices=[('Enable', 'Enable'), ('Disable', 'Disable')], default='Enable', max_length=20),
        ),
    ]
